# .travis.yml using R language
# https://docs.travis-ci.com/user/languages/r

# use r
language: R

# use containers
sudo: false

# cache local R libraries directory:
cache: packages

cran: http://cran.rstudio.com

# only run for pushes to master branch
branches:
  only:
   - master

# install the package and dependencies:
r_packages: 
  - covr
  - lintr

install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'

# Lint
script:
  - ./travis-linter.sh
